# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: alvaro8317udemy
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: first-project
# "service" is the name of this project. This will also be added to your AWS resource names.
service: process-csv-to-image

params:
  default:
    namebucket: alvaro8317
  dev: 
    namebucket: alvaro8317dev

custom:
  pythonRequirements: {}

provider:
  name: aws
  runtime: python3.12

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket:
            Ref: MyBucketOfCsvAndImages
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
          existing: true
    iam:
      role:
        statements:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
            Resource:
              - !GetAtt MyBucketOfCsvAndImages.Arn # Sobre el bucket
              - !Sub ${MyBucketOfCsvAndImages.Arn}/* # Sobre los objetos del bucket
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"
resources:
  Resources:
    MyBucketOfCsvAndImages:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: bucket-csv-images-${param:namebucket}-${sls:stage}
        VersioningConfiguration:
          Status: Enabled
  Outputs:
    MyBucketOfCsvAndImagesOutput:
      Description: Name of the bucket
      Value: !Ref MyBucketOfCsvAndImages