AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Java version of Expense App

Globals:
  Function:
    Timeout: 10
    MemorySize: 512

Resources:
  SpendFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.alvaro8317.expense.handler.SpendHandler::handleRequest
      Runtime: java17
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpenseTable
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpenseTable

  ExpenseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
