version = 0.1

[default]
stack_name = "expense-app-manager-ts"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
[default.deploy.parameters]
stack_name = "expense-app-manager-ts"
resolve_s3 = true
s3_prefix = "expense-app-manager-ts"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
