AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  expense-app-manager-frontend

  App to manage my spends

Resources:
  BucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "expense-app-manager-frontend-sam"
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: "index.html"
  BucketS3Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketS3
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: PublicReadGetObject
          Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource: !Sub arn:aws:s3:::${BucketS3}/*
